export { HeroSection } from "./hero-section"
export { FeaturedProjectsSection } from "./featured-projects-section"
export { FeaturedGallery } from "./featured-gallery"
export { AboutPreview } from "./about-preview"
export { TestimonialsSection } from "./testimonials-section"
export { CTASection } from "./cta-section"
